settings:
  docker:
    parent_image: 992382797823.dkr.ecr.eu-central-1.amazonaws.com/zenml-rlwlcs:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  user_full_name: Paul Iusztin # [First Name(s)] [Last Name]
  links:
    # Medium (only articles that are not under the paid wall work)
    - https://medium.com/data-science/quick-review-to-leap-into-embedded-models-with-proxies-c6f39e24d06d